version: "3.6"
services:
  producer:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: HelloWorld,Producer
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_EXCHANGE: ""
      RABBITMQ_ROUTING_KEY: ""
      RABBITMQ_QUEUE: greeting
  consumer:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: HelloWorld,Consumer
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_EXCHANGE: ""
      RABBITMQ_ROUTING_KEY: ""
      RABBITMQ_QUEUE: greeting