version: "3.6"
services:
  producer:
    build:
      context: .
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: RPC,Producer
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_EXCHANGE: ""
      RABBITMQ_ROUTING_KEY: kern.critical
      RABBITMQ_QUEUE: "rpc_queue"
      RABBITMQ_EXCHANGE_TYPE: topic

  server:
    build:
      context: .
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: RPC,Consumer
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_EXCHANGE: ""
      RABBITMQ_ROUTING_KEY: ""
      RABBITMQ_QUEUE: "rpc_queue"
      RABBITMQ_EXCHANGE_TYPE: ""
